### ISSUE TITLE
Idea: remove app user from dockerfile

### ISSUE THREAD

**Issue by PKuebler** [sourceboat/docker-laravel#25]
The standard user for web applications on Linux systems is "www-data". This user already exists. Therefore the user app is superfluous and is not used anywhere.

**Comment by pehbehbeh** [comment]
I merged #29 although the user home folder `/home/app` is used to store some scripts ([see](https://github.com/sourceboat/docker-laravel/tree/0.10.3/home/app)). We could move these scripts?

@PKuebler @hingew

**Comment by hingew** [comment]
We could move the scripts into `/root/`, @pehbehbeh what do you think ?

**Comment by pehbehbeh** [comment]
Sounds good to me but we need to change all run commands (also in readme).
