### ISSUE TITLE
Idea: remove version headers

### ISSUE THREAD

**Issue by PKuebler** [sourceboat/docker-laravel#27]
Hide the PHP and Nginx version headers to slow down a possible attack.

current response headers:
`X-Powered-By: PHP/7.4.6`
`Server: nginx/1.16.1`

**Comment by hingew** [comment]
https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
https://www.php.net/manual/en/ini.core.php#ini.expose-php
